pragma solidity 0.5.12;

import "@openzeppelin/contracts/token/ERC20/SafeERC20.sol";

import "../interface/IProfitProvider.sol";
import "@nomiclabs/buidler/console.sol";

contract MockProfitProviderUSDx is IProfitProvider {
    using SafeMath for uint256;
    using SafeERC20 for IERC20;

    IERC20 public USDx;

    address public profitFunds;

    uint256 startingPoint;

    constructor(address _USDx, address _profitFunds) public {
        USDx = IERC20(_USDx);
        profitFunds = _profitFunds;
    }

    function getProfitAmount() public returns (uint256) {
        console.log(
            "profitFunds balance %d, startingpoint %d",
            USDx.balanceOf(profitFunds),
            startingPoint
        );
        return USDx.balanceOf(profitFunds).sub(startingPoint);
    }

    /**
     * @dev When the total supply of token is 0, it needs to be called to reset the starting point.
     */
    function resetProfit() external {
        startingPoint = USDx.balanceOf(profitFunds);
    }

    /**
     * @dev Withdraw the interest generated by USDx.
     * @param _amount USDx withdrawal amount.
     * @return Withdraw USDx amount.
     */
    function withdrawProfit(uint256 _amount) external {
        console.log("About to transfer %d from %s", _amount, address(USDx));
        USDx.safeTransferFrom(profitFunds, msg.sender, _amount);
    }
}
