pragma solidity 0.5.12;

interface IInterestProvider {
    function funds() external view returns (address);

    /**
     * @dev Get the total amount of profit, the amount is based on underlying token.
     */
    function getInterestAmount() external returns (uint256);

    /**
     * @dev When the total supply of token is 0, it needs to be called to reset the starting point.
     */
    function resetInterest() external;

    /**
     * @dev Withdraw the interest generated by USDx.
     * @param _amount USDx withdrawal amount.
     * @return Withdraw USDx amount.
     */
    function withdrawInterest(uint256 _amount) external;
}
